development:
  clients:
    default:
      database: simple_crawler_api_db
      hosts:
        - db:27017
      options:
  options:

test:
  clients:
    default:
      database: simple_crawler_api_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
